/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const StickerCategory = IDL.Variant({
  'Art' : IDL.Null,
  'Tech' : IDL.Null,
  'Nature' : IDL.Null,
  'Abstract' : IDL.Null,
  'Other' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Timestamp = IDL.Int;
export const Sticker = IDL.Record({
  'id' : IDL.Nat,
  'blob' : ExternalBlob,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'uploaderPrincipal' : IDL.Principal,
  'category' : StickerCategory,
  'uploadDate' : Timestamp,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addSticker' : IDL.Func(
      [IDL.Text, StickerCategory, IDL.Text, ExternalBlob],
      [IDL.Nat],
      [],
    ),
  'getStickerById' : IDL.Func([IDL.Nat], [IDL.Opt(Sticker)], ['query']),
  'getStickers' : IDL.Func([], [IDL.Vec(Sticker)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const StickerCategory = IDL.Variant({
    'Art' : IDL.Null,
    'Tech' : IDL.Null,
    'Nature' : IDL.Null,
    'Abstract' : IDL.Null,
    'Other' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Timestamp = IDL.Int;
  const Sticker = IDL.Record({
    'id' : IDL.Nat,
    'blob' : ExternalBlob,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'uploaderPrincipal' : IDL.Principal,
    'category' : StickerCategory,
    'uploadDate' : Timestamp,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addSticker' : IDL.Func(
        [IDL.Text, StickerCategory, IDL.Text, ExternalBlob],
        [IDL.Nat],
        [],
      ),
    'getStickerById' : IDL.Func([IDL.Nat], [IDL.Opt(Sticker)], ['query']),
    'getStickers' : IDL.Func([], [IDL.Vec(Sticker)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };